#pragma once

#include "WrapperBase.h"

namespace engine
{

extern Wrapper gPhysicallyBasedRenderingSun;
extern Wrapper gPhysicallyBasedRenderingDayBrightness;
extern Wrapper gPhysicallyBasedRenderingModelDataMipmapLevelOfDetailBias;
extern Wrapper gPhysicallyBasedRenderingBidirectionalReflectanceDistributionFunctionDiffuse;
extern Wrapper gPhysicallyBasedRenderingBidirectionalReflectanceDistributionFunctionDiffusePower;
extern Wrapper gPhysicallyBasedRenderingBidirectionalReflectanceDistributionFunctionSpecular;
extern Wrapper gPhysicallyBasedRenderingBidirectionalReflectanceDistributionFunctionSpecularPower;
extern Wrapper gPhysicallyBasedRenderingExposure;
extern Wrapper gPhysicallyBasedRenderingGamma;
extern Wrapper gColorGradingSaturation;
extern Wrapper gColorGradingContrast;
extern Wrapper gColorGradingTemperature;
extern Wrapper gPhysicallyBasedRenderingLightingSpecular;
extern Wrapper gPhysicallyBasedRenderingLightingSpecularPower;
extern Wrapper gPhysicallyBasedRenderingLighting;
extern Wrapper gPhysicallyBasedRenderingLightingPower;
extern Wrapper gPhysicallyBasedRenderingImageBasedLightingAmbient;
extern Wrapper gPhysicallyBasedRenderingImageBasedLightingDiffuse;
extern Wrapper gPhysicallyBasedRenderingImageBasedLightingDiffusePower;
extern Wrapper gPhysicallyBasedRenderingImageBasedLightingSpecular;
extern Wrapper gPhysicallyBasedRenderingImageBasedLightingSpecularPower;
extern Wrapper gPhysicallyBasedRenderingImageBasedLightingShadowBlend;
extern Wrapper gPhysicallyBasedRenderingImageBasedLightingAmbientColorBlend;
extern Wrapper gPhysicallyBasedRenderingCubemapLevelOfDetailPower;
extern Wrapper gPhysicallyBasedRenderingCubemapLevelOfDetailOffset;
extern Wrapper gPhysicallyBasedRenderingShadowFloor;
extern Wrapper gPhysicallyBasedRenderingSmoke;
extern Wrapper gPhysicallyBasedRenderingEmissive;

} // namespace engine
