#include "DiagnosticReporter.h"
#include "FileManager.h"

#include "Attribution.h"
#include "ExportJobs/ExportAudio.h"
#include "ExportJobs/ExportCubemapIbl.h"
#include "ExportJobs/ExportScene.h"
#include "ExportJobs/ExportIsland.h"
#include "ExportJobs/ExportJob.h"
#include "ExportJobs/ExportModel.h"
#include "ExportJobs/ExportRaw.h"
#include "ExportJobs/ExportShader.h"
#include "ExportJobs/ExportTexture.h"
#include "ExportJobs/Island/BakeIslandIntermediates.h"
#include "ExportJobs/Texture/MigrateLegacyIntermediates.h"
#include "ExportJobs/Texture/RdoSweep.h"
#include "ExportJobs/Texture/Texture.h"

struct DataTypeEntry
{
	std::string_view enumSuffix;
	std::string_view displayName;
	std::string_view headerFile;
};

// Source of truth for the data-type enum, display names, and per-type CRC header
// includes. The order here defines the integer values of the generated DataTypes
// enum and is consumed by the runtime via `kpcDataTypeNames[kDataType...]`.
static constexpr DataTypeEntry kDataTypes[] =
{
	{"Audio",   "Audio",   "Audio.h"},
	{"Scene",   "Scene",   "Scene.h"},
	{"Islands", "Islands", "Islands.h"},
	{"Model",   "Model",   "Model.h"},
	{"Shader",  "Shader",  "Shader.h"},
	{"Texture", "Texture", "Texture.h"},
	{"Raw",     "Raw",     "Raw.h"},
};
static constexpr size_t kDataTypeCount = std::size(kDataTypes);

static void WriteIfChanged(const std::string& rContent, const std::filesystem::path& rPath, const char* logName)
{
	if (!common::ContentsEqual(rContent, rPath))
	{
		if (gpFileManager->EnsureLocal(FileManager::OutputRoot::kData) == FileManager::EnsureLocalResult::kCancelled)
		{
			throw diagnostic::AlreadyReportedError("Output materialization cancelled");
		}
		std::fstream stream(rPath, std::ios::out | std::ios::binary);
		stream << rContent;
		stream.close();
		VERIFY_SUCCESS(stream.good());
		LOG(kDefault, kDebug, "Re-generated {}", logName);
	}
}

template <IsExportJob T>
static void WriteCrcHeader(const std::filesystem::path& rOutPath, const std::vector<std::unique_ptr<T>>& rJobs)
{
	std::fstream stream(rOutPath, std::ios::out | std::ios::binary);
	stream << "#pragma once" << std::endl;
	stream << std::endl;
	stream << "// This file is automatically generated by the Data Packer" << std::endl;
	stream << "// To add a Crc to this file place your data file in: BrokenEngine/Engine/Data" << std::endl;
	stream << "// or BrokenEngine/Projects/YOUR_PROJECT/Data" << std::endl;
	stream << "// Then re-build and the Data Packer will run automatically as a pre-build event" << std::endl;
	stream << std::endl;
	stream << "namespace data" << std::endl;
	stream << "{" << std::endl;
	stream << std::endl;
	for (const std::unique_ptr<T>& rpJob : rJobs)
	{
		stream << "inline constexpr common::crc_t k" << common::PathToCppVariable(rpJob->mRelativeFile) << "Crc = " << rpJob->mCrc << "ull;" << std::endl;
	}
	stream << std::endl;
	stream << "} // namespace data" << std::endl;
	stream.close();
	VERIFY_SUCCESS(stream.good());
}

static bool IsFileLockedError(DWORD uiError)
{
	return uiError == ERROR_SHARING_VIOLATION || uiError == ERROR_LOCK_VIOLATION;
}

static bool IsFileLockedError(const std::error_code& rError)
{
	// std::filesystem reports Win32 codes through std::system_category on Windows
	return rError.category() == std::system_category() && IsFileLockedError(static_cast<DWORD>(rError.value()));
}

// Publishes the manifest and pack over the previous output. A running BrokenEngineSandbox client or server keeps its
// packs open share-read-only for the whole process lifetime, so without this the pack rename fails after the manifest
// already published, leaving a torn publish. Returns false when the user cancels the export at the retry prompt.
static bool PublishManifestAndPack(const std::filesystem::path& rTemporaryManifestFile, const std::filesystem::path& rManifestFile, const std::filesystem::path& rTemporaryPackFile, const std::filesystem::path& rPackFile)
{
	const std::string lockedFailure = std::format("\"{}\" is locked by a running BrokenEngineSandbox client or server.", rPackFile.string());

	bool bManifestPublished = false;
	// Empty means no prompt is pending; otherwise it is the sentence describing why publishing failed
	std::string pendingFailure;
	while (true)
	{
		// Requesting DELETE access fails against a client or server already holding the pack share-read-only, so an
		// already-running one is detected before the manifest publishes and the common case prompts with nothing torn yet.
		std::unique_ptr<void, decltype(&CloseHandle)> pProbe(nullptr, &CloseHandle);
		if (pendingFailure.empty() && std::filesystem::exists(rPackFile))
		{
			HANDLE hProbe = CreateFileW(rPackFile.native().c_str(), DELETE, FILE_SHARE_READ | FILE_SHARE_WRITE | FILE_SHARE_DELETE, nullptr, OPEN_EXISTING, 0, nullptr);
			if (hProbe != INVALID_HANDLE_VALUE)
			{
				pProbe.reset(hProbe);
			}
			else if (IsFileLockedError(GetLastError()))
			{
				pendingFailure = lockedFailure;
			}
			// Any other probe failure falls through to the renames, which report the real cause: the manifest rename by
			// throwing, the pack rename through the prompt below
		}

		if (!pendingFailure.empty())
		{
			diagnostic::Record record
			{
				.eSeverity = diagnostic::Severity::kWarning,
				.title = "Data Packer - Cannot Publish Output",
				.message = std::format("{}\n\nClose it and press OK to retry, or press Cancel to abort the export.", pendingFailure),
				.eButtons = diagnostic::ButtonContract::kOkCancel,
				.eIcon = diagnostic::ModalIcon::kWarning,
			};
			if (diagnostic::Report(record) == diagnostic::ButtonResult::kCancelled)
			{
				return false;
			}
			pendingFailure.clear();
			continue;
		}

		// Manifest before pack, preserving the commit-point ordering and kill semantics documented at the header publish in RunDirtyExport
		std::error_code renameError;
		if (!bManifestPublished)
		{
			std::filesystem::rename(rTemporaryManifestFile, rManifestFile, renameError);
			if (renameError)
			{
				if (!IsFileLockedError(renameError))
				{
					throw std::filesystem::filesystem_error("Failed to publish manifest", rTemporaryManifestFile, rManifestFile, renameError);
				}
				// A lock that survives the probe must prompt rather than spin, so the next pass skips straight to the prompt
				pendingFailure = lockedFailure;
				continue;
			}
			bManifestPublished = true;
		}

		// Windows refuses to replace a destination that has any open handle, including this process's own, so the probe
		// must go first. A client that opens the pack in that gap fails the rename below and reaches the prompt.
		pProbe.reset();

		std::filesystem::rename(rTemporaryPackFile, rPackFile, renameError);
		if (!renameError)
		{
			return true;
		}
		// The manifest is already published, so every cause must prompt rather than throw and strand a torn publish
		pendingFailure = std::format("Failed to publish \"{}\": {}", rPackFile.string(), renameError.message());
	}
}

static std::optional<uint64_t> GetReadableFileSize(const std::filesystem::path& rPath)
{
	std::error_code fileSizeError;
	const uintmax_t uiFileSizeValue = std::filesystem::file_size(rPath, fileSizeError);
	if (fileSizeError)
	{
		return std::nullopt;
	}
	if (uiFileSizeValue > std::numeric_limits<uint64_t>::max())
	{
		return std::nullopt;
	}
	if (uiFileSizeValue > static_cast<uintmax_t>(std::numeric_limits<std::streamoff>::max()))
	{
		return std::nullopt;
	}
	return static_cast<uint64_t>(uiFileSizeValue);
}

static bool LoadPublishedManifestChunkTable(const std::filesystem::path& rManifestFile, std::fstream& rManifestFileStream, int64_t iManifestChunkCount, std::vector<common::ChunkLocation>& rManifestChunkLocations)
{
	static constexpr uint64_t kuiChunkTableOffset = static_cast<uint64_t>(common::RoundUp<int64_t, common::kiAlignmentBytes>(static_cast<int64_t>(sizeof(common::DataHeader))));

	const std::optional<uint64_t> optionalManifestFileSize = GetReadableFileSize(rManifestFile);
	if (!optionalManifestFileSize.has_value())
	{
		return false;
	}

	const uint64_t uiManifestFileSize = optionalManifestFileSize.value();
	if (uiManifestFileSize < kuiChunkTableOffset)
	{
		return false;
	}

	const uint64_t uiManifestTableBytes = uiManifestFileSize - kuiChunkTableOffset;
	const uint64_t uiMaxChunks = uiManifestTableBytes / static_cast<uint64_t>(sizeof(common::ChunkLocation));
	if (iManifestChunkCount < 0)
	{
		return false;
	}
	if (static_cast<uint64_t>(iManifestChunkCount) > uiMaxChunks)
	{
		return false;
	}
	if (static_cast<uint64_t>(iManifestChunkCount) > static_cast<uint64_t>(std::numeric_limits<size_t>::max()))
	{
		return false;
	}
	if (static_cast<uint64_t>(iManifestChunkCount) > static_cast<uint64_t>(std::numeric_limits<std::streamsize>::max()) / sizeof(common::ChunkLocation))
	{
		return false;
	}

	const uint64_t uiChunkTableBytes = static_cast<uint64_t>(iManifestChunkCount) * sizeof(common::ChunkLocation);

	try
	{
		rManifestChunkLocations.resize(static_cast<size_t>(iManifestChunkCount));
	}
	catch (const std::exception&)
	{
		return false;
	}

	rManifestFileStream.seekg(static_cast<std::streamoff>(kuiChunkTableOffset), std::ios::beg);
	if (!rManifestFileStream)
	{
		return false;
	}
	if (uiChunkTableBytes == 0)
	{
		return true;
	}

	rManifestFileStream.read(reinterpret_cast<char*>(rManifestChunkLocations.data()), static_cast<std::streamsize>(uiChunkTableBytes));
	return rManifestFileStream && rManifestFileStream.gcount() == static_cast<std::streamsize>(uiChunkTableBytes);
}

static bool LoadPublishedManifest(const std::filesystem::path& rManifestFile, int64_t& riManifestChunkCount, std::vector<common::ChunkLocation>& rManifestChunkLocations)
{
	// A lone kiVersion bump must re-export everything — the engine ASSERTs on a stale-version manifest and there is no recovery CLI
	common::DataHeader dataHeader {};
	std::fstream manifestFileStream(rManifestFile, std::ios::in | std::ios::binary);
	manifestFileStream.read(reinterpret_cast<char*>(&dataHeader), sizeof(dataHeader));
	const bool bDirty = !manifestFileStream || dataHeader.iMagic != common::DataHeader::kiMagic || dataHeader.iVersion != common::DataHeader::kiVersion;
	riManifestChunkCount = dataHeader.iChunkCount;
	return !bDirty && LoadPublishedManifestChunkTable(rManifestFile, manifestFileStream, riManifestChunkCount, rManifestChunkLocations);
}

static bool ValidatePublishedPackLayout(const std::filesystem::path& rPackFile, const std::vector<common::ChunkLocation>& rManifestChunkLocations)
{
	const std::optional<uint64_t> optionalPackFileSize = GetReadableFileSize(rPackFile);
	if (!optionalPackFileSize.has_value())
	{
		return false;
	}

	std::fstream packFileStream(rPackFile, std::ios::in | std::ios::binary);
	if (!packFileStream)
	{
		return false;
	}

	static constexpr uint64_t kuiAlignmentBytes = static_cast<uint64_t>(common::kiAlignmentBytes);
	uint64_t uiExpectedOffset = 0;
	for (const common::ChunkLocation& rChunkLocation : rManifestChunkLocations)
	{
		if (rChunkLocation.uiOffset != uiExpectedOffset
			|| rChunkLocation.uiOffset % kuiAlignmentBytes != 0
			|| rChunkLocation.uiOffset > optionalPackFileSize.value()
			|| rChunkLocation.uiSize < static_cast<uint64_t>(common::kiChunkDataOffset)
			|| rChunkLocation.uiSize > optionalPackFileSize.value() - rChunkLocation.uiOffset)
		{
			return false;
		}

		common::ChunkHeader chunkHeader {};
		packFileStream.seekg(static_cast<std::streamoff>(rChunkLocation.uiOffset), std::ios::beg);
		if (!packFileStream)
		{
			return false;
		}
		packFileStream.read(reinterpret_cast<char*>(&chunkHeader), sizeof(chunkHeader));
		if (!packFileStream
			|| packFileStream.gcount() != static_cast<std::streamsize>(sizeof(chunkHeader))
			|| chunkHeader.iMagic != common::ChunkHeader::kiMagic
			|| chunkHeader.crc != rChunkLocation.crc)
		{
			return false;
		}

		const uint64_t uiChunkEnd = rChunkLocation.uiOffset + rChunkLocation.uiSize;
		const uint64_t uiPadding = (kuiAlignmentBytes - (uiChunkEnd % kuiAlignmentBytes)) % kuiAlignmentBytes;
		if (uiChunkEnd > std::numeric_limits<uint64_t>::max() - uiPadding)
		{
			return false;
		}
		uiExpectedOffset = uiChunkEnd + uiPadding;
	}

	return uiExpectedOffset == optionalPackFileSize.value();
}

template <IsExportJob T>
static std::vector<std::unique_ptr<T>> DiscoverExportJobsAndAggregateDirty(const std::filesystem::path& rPackFile, const std::vector<common::ChunkLocation>& rManifestChunkLocations, bool& rbDirty)
{
	std::vector<std::unique_ptr<T>> exportJobs;
	for (const std::filesystem::path& rBaseDirectory : gpFileManager->mpInputDirectories)
	{
		for (const std::filesystem::directory_entry& rDirectoryEntry : std::filesystem::recursive_directory_iterator(rBaseDirectory))
		{
			std::optional<common::ChunkFlags_t> optionalChunkFlags = T::Handles(rDirectoryEntry);
			if (optionalChunkFlags.has_value())
			{
				std::unique_ptr<T>& rpExportJob = exportJobs.emplace_back(std::make_unique<T>(optionalChunkFlags.value(), rDirectoryEntry.path()));
				rbDirty |= rpExportJob->CheckDirty(rPackFile);
			}
		}
	}

	// An added, deleted, or renamed source asset changes which paths the published .pack/.manifest (and
	// the constants in the generated header) describe, but dirties nothing above: the per-job cache is
	// keyed by path and shared across worktrees, so a path exported earlier under another branch checks
	// clean the moment it comes back, and a rename that preserves the count hides behind an equal count.
	// The manifest's chunk key and ExportJob::mCrc are the same quantity — Crc(relative path) — so
	// comparing the two path-CRC sets catches every such difference, count changes included. Neither
	// side is in numeric order (jobs follow directory iteration, manifest chunks follow lowered path),
	// hence the sorts. Skipped when already dirty, which also covers a missing or invalid manifest.
	if (!rbDirty)
	{
		std::vector<common::crc_t> manifestPathCrcs;
		manifestPathCrcs.reserve(rManifestChunkLocations.size());
		for (const common::ChunkLocation& rChunkLocation : rManifestChunkLocations)
		{
			manifestPathCrcs.push_back(rChunkLocation.crc);
		}

		std::vector<common::crc_t> jobPathCrcs;
		jobPathCrcs.reserve(exportJobs.size());
		for (const std::unique_ptr<T>& rpExportJob : exportJobs)
		{
			jobPathCrcs.push_back(rpExportJob->mCrc);
		}

		std::sort(manifestPathCrcs.begin(), manifestPathCrcs.end());
		std::sort(jobPathCrcs.begin(), jobPathCrcs.end());
		if (manifestPathCrcs != jobPathCrcs)
		{
			LOG(kDefault, kDebug, "\"{}\" asset path set differs from the published manifest ({} jobs, {} manifest chunks); re-exporting", T::kName, jobPathCrcs.size(), manifestPathCrcs.size());
			rbDirty = true;
		}
	}

	// Each job commits its .meta fingerprint at export time on a worker thread, but the pack/manifest
	// rename below happens later on this thread — a kill in that window leaves every fingerprint clean
	// while the published pack is stale, and nothing above compares the two. A fingerprint newer than
	// the published pack therefore dirties the aggregate; the jobs themselves stay clean, so the pack
	// is reassembled from the cached chunks without re-exporting.
	if (!rbDirty)
	{
		std::error_code packError;
		std::filesystem::file_time_type packTime = std::filesystem::last_write_time(rPackFile, packError);
		for (const std::unique_ptr<T>& rpExportJob : exportJobs)
		{
			std::error_code metadataError;
			std::filesystem::file_time_type metadataTime = std::filesystem::last_write_time(rpExportJob->mCacheMetadataFile, metadataError);
			if (packError || metadataError || packTime < metadataTime)
			{
				LOG(kDefault, kDebug, "Pack file \"{}\" is older than fingerprint \"{}\"", rPackFile.string(), rpExportJob->mCacheMetadataFile.string());
				rbDirty = true;
				break;
			}
		}
	}

	return exportJobs;
}

template <IsExportJob T>
static void SortAndCheckDuplicateExportJobs(std::vector<std::unique_ptr<T>>& rExportJobs)
{
	// Sort by relative path to ensure chunks are in same order inside the file (for more efficient Steam patching)
	std::sort(rExportJobs.begin(), rExportJobs.end(), [](const std::unique_ptr<T>& rpLeft, const std::unique_ptr<T>& rpRight)
	{
		return common::ToLower(rpLeft->mRelativeFile) < common::ToLower(rpRight->mRelativeFile);
	});

	// The two input roots (engine Data + project Data) can hold the same relative path; ExportJob
	// derives mRelativeFile/mCrc (mCrc = Crc(mRelativeFile)) from whichever root matched, so the
	// duplicates would silently produce two manifest entries with one CRC (ambiguous runtime lookup)
	// plus two identically named generated constants. Case-folded duplicates sort adjacent under the
	// comparator above, so the adjacent-pair walk catches every such collision; guaranteeing unique
	// lowered keys also makes the sort fully deterministic (no tied keys for std::sort to order
	// arbitrarily). A CRC equality check is intentionally omitted: identical paths already trip the
	// case-folded compare, and a hash collision between two DISTINCT paths is astronomically unlikely
	// and would not sort adjacent anyway — not the bug class this guards.
	for (size_t uiJob = 1; uiJob < rExportJobs.size(); ++uiJob)
	{
		const T& rPrevious = *rExportJobs.at(uiJob - 1);
		const T& rCurrent = *rExportJobs.at(uiJob);
		if (common::ToLower(rPrevious.mRelativeFile) == common::ToLower(rCurrent.mRelativeFile))
		{
			throw std::runtime_error(std::format("\"{}\" export has a duplicate asset: \"{}\" and \"{}\" resolve to the same relative path across input roots \"{}\" and \"{}\". Rename or remove one so each chunk keeps a unique manifest key.", T::kName, rPrevious.mInputPath.string(), rCurrent.mInputPath.string(), gpFileManager->mpInputDirectories[0].string(), gpFileManager->mpInputDirectories[1].string()));
		}
	}
}

template <IsExportJob T>
static std::vector<diagnostic::ExportFailure> WriteTemporaryExportFiles(const std::filesystem::path& rTemporaryManifestFile, const std::filesystem::path& rTemporaryPackFile, std::vector<std::unique_ptr<T>>& rExportJobs)
{
	// Open temporary manifest file and write header
	std::fstream temporaryManifestFileStream(rTemporaryManifestFile, std::ios::out | std::ios::binary);

	common::DataHeader dataHeader {};
	dataHeader.iMagic = common::DataHeader::kiMagic;
	dataHeader.iVersion = common::DataHeader::kiVersion;
	dataHeader.iChunkCount = rExportJobs.size();
	temporaryManifestFileStream.write(reinterpret_cast<char*>(&dataHeader), sizeof(dataHeader));
	common::AlignOutputStream(temporaryManifestFileStream);

	// Open temporary pack file
	std::fstream temporaryPackFileStream(rTemporaryPackFile, std::ios::out | std::ios::binary);

	std::vector<diagnostic::ExportFailure> failures;
	failures.reserve(rExportJobs.size() + 1);
	for (std::unique_ptr<T>& rpExportJob : rExportJobs)
	{
		try
		{
			std::vector<std::byte>& rData = rpExportJob->mFuture.get();

			common::ChunkLocation chunkLocation =
			{
				.crc = rpExportJob->mCrc,
				.uiOffset = static_cast<uint64_t>(temporaryPackFileStream.tellp()),
				.uiSize = rData.size(),
				.contentCrc = rData.empty() ? common::kCrcSeed : common::Crc(rData.data(), static_cast<int64_t>(rData.size())),
			};
			temporaryManifestFileStream.write(reinterpret_cast<char*>(&chunkLocation), sizeof(chunkLocation));

			temporaryPackFileStream.write(reinterpret_cast<char*>(rData.data()), rData.size());
			common::AlignOutputStream(temporaryPackFileStream);
		}
		catch (const std::exception& rException)
		{
			failures.push_back({.assetPath = rpExportJob->mInputPath, .message = rException.what()});
		}
	}

	temporaryManifestFileStream.close();
	temporaryPackFileStream.close();

	// Trust boundary: a disk-full / IO failure during the writes above sets badbit but leaves failures
	// empty, so without this check the success path would rename truncated manifest/pack output over the good files.
	if (!temporaryManifestFileStream.good() || !temporaryPackFileStream.good())
	{
		failures.push_back({.message = std::format("Stream write failed for \"{}\" manifest/pack output", T::kName)});
	}

	return failures;
}

template <IsExportJob T>
static bool RunDirtyExport(const std::filesystem::path& rManifestFile, const std::filesystem::path& rPackFile, const std::filesystem::path& rHeaderFile, std::vector<std::unique_ptr<T>>& rExportJobs)
{
	if (gpFileManager->EnsureLocal(FileManager::OutputRoot::kData) == FileManager::EnsureLocalResult::kCancelled)
	{
		throw diagnostic::AlreadyReportedError("Output materialization cancelled");
	}

	LOG(kDefault, kDebug, "\"{}\" is dirty, running export", T::kName);
	ScopedLogIndent scopedLogIndent;

	SortAndCheckDuplicateExportJobs(rExportJobs);

	// Run the jobs
	for (std::unique_ptr<T>& rpExportJob : rExportJobs)
	{
		rpExportJob->mFuture = std::async(std::launch::async, &T::RunExport, rpExportJob.get());
	}

	// Stage beside the finals, never in the cache: the cache lives under LocalAppData and can be on another
	// volume, where the publish renames below degrade to copy-then-delete and a kill mid-copy leaves a
	// truncated manifest/pack/header where a complete one used to be. Same-directory renames stay atomic.
	std::filesystem::path temporaryManifestFile = gpFileManager->mOutputDirectory;
	temporaryManifestFile /= T::kName;
	temporaryManifestFile += ".manifest.tmp";

	std::filesystem::path temporaryPackFile = gpFileManager->mOutputDirectory;
	temporaryPackFile /= T::kName;
	temporaryPackFile += ".pack.tmp";

	std::filesystem::path temporaryHeaderFile = gpFileManager->mOutputDirectory;
	temporaryHeaderFile /= T::kName;
	temporaryHeaderFile += ".h.tmp";

	std::vector<diagnostic::ExportFailure> failures = WriteTemporaryExportFiles(temporaryManifestFile, temporaryPackFile, rExportJobs);

	bool bFailed = !failures.empty();
	if (bFailed)
	{
		diagnostic::Record record
		{
			.eSeverity = diagnostic::Severity::kError,
			.title = "Data Packer - Export Failed",
			.message = "One or more export jobs failed",
			.eButtons = diagnostic::ButtonContract::kOk,
			.eIcon = diagnostic::ModalIcon::kNone,
			.exportFailures = std::move(failures),
		};
		diagnostic::Report(record);

		std::filesystem::remove(temporaryManifestFile);
		std::filesystem::remove(temporaryPackFile);
	}
	else
	{
		WriteCrcHeader(temporaryHeaderFile, rExportJobs);

		// Only copy header if it has changed (causes game re-compilation otherwise). The header must publish
		// before the pack: the pack rename is the commit point every dirty check keys off, so a header
		// renamed after it would strand on a kill — pack/manifest new, every fingerprint older than the
		// fresh pack, and the header check above only tests existence, never staleness. Publishing first
		// cannot strand it: the constants are Crc(mRelativeFile), path-derived only, so the header changes
		// only when the asset path set changes, and every such cause re-dirties against the still-old pack
		// next run — any add, removal, or rename trips the path-CRC set comparison in
		// DiscoverExportJobsAndAggregateDirty, and a regenerated missing header already matches the pack.
		if (!common::ContentsEqual(temporaryHeaderFile, rHeaderFile))
		{
			std::filesystem::rename(temporaryHeaderFile, rHeaderFile);
		}
		else
		{
			std::filesystem::remove(temporaryHeaderFile);
		}

		if (!PublishManifestAndPack(temporaryManifestFile, rManifestFile, temporaryPackFile, rPackFile))
		{
			// Cancelled at the publish prompt: discard the temporaries and fail this export type
			std::filesystem::remove(temporaryManifestFile);
			std::filesystem::remove(temporaryPackFile);
			bFailed = true;
		}
	}

	return !bFailed;
}

template <IsExportJob T>
bool RunExportJobs()
{
	bool bDirty = gpFileManager->mbCleanExport;

	std::filesystem::path manifestFile = gpFileManager->mOutputDirectory;
	manifestFile /= T::kName;
	manifestFile += ".manifest";
	bDirty |= !std::filesystem::exists(manifestFile);

	int64_t iManifestChunkCount = -1;
	std::vector<common::ChunkLocation> manifestChunkLocations;
	if (!bDirty && !LoadPublishedManifest(manifestFile, iManifestChunkCount, manifestChunkLocations))
	{
		bDirty = true;
	}

	std::filesystem::path packFile = gpFileManager->mOutputDirectory;
	packFile /= T::kName;
	packFile += ".pack";
	bDirty |= !std::filesystem::exists(packFile);

	std::filesystem::path headerFile = gpFileManager->mOutputDirectory;
	headerFile /= T::kName;
	headerFile += ".h";
	bDirty |= !std::filesystem::exists(headerFile);

	std::vector<std::unique_ptr<T>> exportJobs = DiscoverExportJobsAndAggregateDirty<T>(packFile, manifestChunkLocations, bDirty);

	if (!bDirty && !ValidatePublishedPackLayout(packFile, manifestChunkLocations))
	{
		bDirty = true;
	}

	if (!bDirty)
	{
		return true;
	}

	return RunDirtyExport(manifestFile, packFile, headerFile, exportJobs);
}

template <typename... Ts>
static bool RunAllMainExports()
{
	// Comma fold (not `&& ...`) so every export runs even if an earlier one fails;
	// matches the original explicit `bSuccess &= RunExportJobs<...>()` sequence.
	bool bSuccess = true;
	((bSuccess &= RunExportJobs<Ts>()), ...);
	return bSuccess;
}

static void GenerateDataTypesHeader(const std::filesystem::path& rOutPath)
{
	std::stringstream content;
	content << "#pragma once" << std::endl;
	content << std::endl;
	content << "// This file is automatically generated by the Data Packer" << std::endl;
	content << std::endl;
	content << "namespace data" << std::endl;
	content << "{" << std::endl;
	content << std::endl;
	content << "enum DataTypes" << std::endl;
	content << "{" << std::endl;
	for (const DataTypeEntry& rEntry : kDataTypes)
	{
		content << "\tkDataType" << rEntry.enumSuffix << "," << std::endl;
	}
	content << "" << std::endl;
	content << "\tkDataTypeCount" << std::endl;
	content << "};" << std::endl;
	content << std::endl;
	content << "inline constexpr const char* kpcDataTypeNames[kDataTypeCount] =" << std::endl;
	content << "{" << std::endl;
	for (size_t i = 0; i < kDataTypeCount; ++i)
	{
		content << "\t\"" << kDataTypes[i].displayName << "\"";
		if (i + 1 < kDataTypeCount)
		{
			content << ",";
		}
		content << std::endl;
	}
	content << "};" << std::endl;
	content << std::endl;
	content << "} // namespace data" << std::endl;

	WriteIfChanged(content.str(), rOutPath, "DataTypes.h");
}

static void GenerateDataHeader(const std::filesystem::path& rOutPath)
{
	std::stringstream content;
	content << "#pragma once" << std::endl;
	content << std::endl;
	content << "// This file is automatically generated by the Data Packer" << std::endl;
	content << std::endl;
	content << "#include \"DataTypes.h\"" << std::endl;
	content << std::endl;
	for (const DataTypeEntry& rEntry : kDataTypes)
	{
		content << "#include \"" << rEntry.headerFile << "\"" << std::endl;
	}

	WriteIfChanged(content.str(), rOutPath, "Data.h");
}

bool MainThread(int argc, char* argv[])
{
	common::ThreadLocal threadLocal(1024, std::nullopt, false);

	LOG(kDefault, kDebug, "\nData Packer");
	ScopedLogIndent scopedLogIndent;

	VERIFY_SUCCESS(XMVerifyCPUSupport());

	Texture::StaticInit();

	auto pFileManager = std::make_unique<FileManager>(std::span(argv, argc));

	MigrateLegacyIntermediates();

	bool bSuccess = true;

	// Scene and Island need to be first as they can create new textures and models
	bSuccess &= RunExportJobs<ExportScene>();
	BakeIslandIntermediates();
	bSuccess &= RunExportJobs<ExportIsland>();

	GenerateIrradianceCubemaps();
	GeneratePreFilteredCubemaps();

	bSuccess &= RunAllMainExports<ExportAudio, ExportModel, ExportShader, ExportTexture, ExportRaw>();

	GenerateDataTypesHeader(gpFileManager->mOutputDirectory / "DataTypes.h");
	GenerateDataHeader(gpFileManager->mOutputDirectory / "Data.h");

	// Copy license files from ThirdParty directories to Attribution directory in output
	attribution::CopyThirdPartyLicenses();

	LOG(kDefault, kDebug, "");

	return bSuccess;
}

bool MaterializeData(char* argv[])
{
	common::ThreadLocal threadLocal(1024, std::nullopt, false);
	std::array<char*, 4> fileManagerArguments { argv[0], argv[2], argv[3], argv[4] };
	auto pFileManager = std::make_unique<FileManager>(fileManagerArguments, FileManager::InitializationMode::kDataOnly);
	return gpFileManager->EnsureLocal(FileManager::OutputRoot::kData) != FileManager::EnsureLocalResult::kCancelled;
}

static bool RunCommand(int argc, char* argv[])
{
	if (argc >= 2 && std::string_view(argv[1]) == "--materialize-data")
	{
		// CLI trust boundary: data materialization takes exactly the two input roots and output Data path
		if (argc != 5)
		{
			std::printf("--materialize-data requires exactly <engine-data> <project-data> <output-data>\n");
			return false;
		}
		return MaterializeData(argv);
	}
	if (argc >= 2 && std::string_view(argv[1]).starts_with("--rdo-sweep"))
	{
		// CLI trust boundary: each sweep mode takes exactly one image/intermediate path
		if (argc != 3)
		{
			std::printf("%s requires exactly one <image path> argument\n", argv[1]);
			return false;
		}
		common::ThreadLocal threadLocal(1024, std::nullopt, false);
		Texture::StaticInit();
		if (std::string_view(argv[1]) == "--rdo-sweep")
		{
			return RunRdoSweep(argv[2]) == 0;
		}
		if (std::string_view(argv[1]) == "--rdo-sweep-full")
		{
			return RunRdoSweepFull(argv[2]) == 0;
		}
		if (std::string_view(argv[1]) == "--rdo-sweep-validate")
		{
			return RunRdoSweepValidate(argv[2]) == 0;
		}
		std::printf("Unknown mode %s\n", argv[1]);
		return false;
	}
	return MainThread(argc, argv);
}

static bool RunCommandWithExceptionHandling(int argc, char* argv[])
{
	bool bSuccess = false;
	try
	{
		bSuccess = RunCommand(argc, argv);
	}
	catch (const diagnostic::AlreadyReportedError&)
	{
	}
	catch (const std::exception& rException)
	{
		const std::string message = rException.what()[0] == '\0' ? "Empty std::exception message escaped DataPacker" : rException.what();
		diagnostic::Record record
		{
			.eSeverity = diagnostic::Severity::kError,
			.title = "Data Packer - std::exception",
			.message = message,
			.eButtons = diagnostic::ButtonContract::kOk,
			.eIcon = diagnostic::ModalIcon::kNone,
		};
		diagnostic::Report(record);
	}
	catch (...)
	{
		diagnostic::Record record
		{
			.eSeverity = diagnostic::Severity::kError,
			.title = "Data Packer - Unknown exception",
			.message = "Unknown non-standard exception escaped DataPacker",
			.eButtons = diagnostic::ButtonContract::kOk,
			.eIcon = diagnostic::ModalIcon::kNone,
		};
		diagnostic::Report(record);
	}
	return bSuccess;
}

int main(int argc, char* argv[])
{
	// Prevent multiple instances from running simultaneously
	HANDLE hMutex = CreateMutex(nullptr, TRUE, "BrokenEngineDataPacker");
	if (hMutex == nullptr)
	{
		const DWORD uiError = GetLastError();
		diagnostic::Record record
		{
			.eSeverity = diagnostic::Severity::kError,
			.title = "Data Packer - std::exception",
			.message = std::format("CreateMutex failed (Win32 {})", uiError),
			.eButtons = diagnostic::ButtonContract::kOk,
			.eIcon = diagnostic::ModalIcon::kNone,
		};
		diagnostic::Report(record);
		return 1;
	}

	// A handle for an existing mutex is not owned until the wait succeeds, so failed waits only close it.
	bool bOwnsMutex = true;
	auto mutexDeleter = [&bOwnsMutex](void* pHandle)
	{
		if (bOwnsMutex)
		{
			ReleaseMutex(pHandle);
		}
		CloseHandle(pHandle);
	};
	std::unique_ptr<void, decltype(mutexDeleter)> pMutex(hMutex, mutexDeleter);
	if (GetLastError() == ERROR_ALREADY_EXISTS)
	{
		bOwnsMutex = false;
		std::printf("DataPacker is already running, waiting...\n");
		const DWORD uiWaitResult = WaitForSingleObject(hMutex, INFINITE);
		if (uiWaitResult == WAIT_FAILED)
		{
			const DWORD uiError = GetLastError();
			diagnostic::Record record
			{
				.eSeverity = diagnostic::Severity::kError,
				.title = "Data Packer - std::exception",
				.message = std::format("WaitForSingleObject failed (Win32 {})", uiError),
				.eButtons = diagnostic::ButtonContract::kOk,
				.eIcon = diagnostic::ModalIcon::kNone,
			};
			diagnostic::Report(record);
			return 1;
		}
		if (uiWaitResult != WAIT_OBJECT_0 && uiWaitResult != WAIT_ABANDONED)
		{
			diagnostic::Record record
			{
				.eSeverity = diagnostic::Severity::kError,
				.title = "Data Packer - std::exception",
				.message = std::format("WaitForSingleObject returned unexpected result {}", uiWaitResult),
				.eButtons = diagnostic::ButtonContract::kOk,
				.eIcon = diagnostic::ModalIcon::kNone,
			};
			diagnostic::Report(record);
			return 1;
		}
		bOwnsMutex = true;
	}

	bool bSuccess = false;

	if (IsDebuggerPresent() == TRUE)
	{
		bSuccess = RunCommand(argc, argv);
	}
	else
	{
		bSuccess = RunCommandWithExceptionHandling(argc, argv);
	}

	fflush(stdout);
	return bSuccess ? 0 : 1;
}

#if defined(_CRTDBG_MAP_ALLOC)

[[nodiscard]] _Ret_notnull_ _Post_writable_byte_size_(n) void* operator new(std::size_t n) noexcept(false) { void* p = std::malloc(n); __assume(p != nullptr); return p; }
[[nodiscard]] _Ret_notnull_ _Post_writable_byte_size_(n) void* operator new[](std::size_t n) noexcept(false) { void* p = std::malloc(n); __assume(p != nullptr); return p; }
[[nodiscard]] _Ret_maybenull_ _Success_(return != NULL) _Post_writable_byte_size_(n) void* operator new  (std::size_t n, const std::nothrow_t&) noexcept { return std::malloc(n); }
[[nodiscard]] _Ret_maybenull_ _Success_(return != NULL) _Post_writable_byte_size_(n) void* operator new[](std::size_t n, const std::nothrow_t&) noexcept { return std::malloc(n); }
[[nodiscard]] _Ret_notnull_ _Post_writable_byte_size_(n) void* operator new  (std::size_t n, std::align_val_t al) noexcept(false) { void* p = _aligned_malloc(n, static_cast<size_t>(al)); __assume(p != nullptr); return p; }
[[nodiscard]] _Ret_notnull_ _Post_writable_byte_size_(n) void* operator new[](std::size_t n, std::align_val_t al) noexcept(false) { void* p = _aligned_malloc(n, static_cast<size_t>(al)); __assume(p != nullptr); return p; }
[[nodiscard]] _Ret_maybenull_ _Success_(return != NULL) _Post_writable_byte_size_(n) void* operator new  (std::size_t n, std::align_val_t al, const std::nothrow_t&) noexcept { return _aligned_malloc(n, static_cast<size_t>(al)); }
[[nodiscard]] _Ret_maybenull_ _Success_(return != NULL) _Post_writable_byte_size_(n) void* operator new[](std::size_t n, std::align_val_t al, const std::nothrow_t&) noexcept { return _aligned_malloc(n, static_cast<size_t>(al)); }

void operator delete(void* p) noexcept { std::free(p); }
void operator delete[](void* p) noexcept { std::free(p); }
void operator delete  (void* p, const std::nothrow_t&) noexcept { std::free(p); }
void operator delete[](void* p, const std::nothrow_t&) noexcept { std::free(p); }
void operator delete  (void* p, std::size_t) noexcept { std::free(p); }
void operator delete[](void* p, std::size_t) noexcept { std::free(p); }
void operator delete  (void* p, std::align_val_t) noexcept { _aligned_free(p); }
void operator delete[](void* p, std::align_val_t) noexcept { _aligned_free(p); }
void operator delete  (void* p, std::size_t, std::align_val_t) noexcept { _aligned_free(p); }
void operator delete[](void* p, std::size_t, std::align_val_t) noexcept { _aligned_free(p); }
void operator delete  (void* p, std::align_val_t, const std::nothrow_t&) noexcept { _aligned_free(p); }
void operator delete[](void* p, std::align_val_t, const std::nothrow_t&) noexcept { _aligned_free(p); }

struct CrtBreakAllocSetter
{
	CrtBreakAllocSetter()
	{
		_CrtSetDbgFlag(_CRTDBG_ALLOC_MEM_DF | _CRTDBG_LEAK_CHECK_DF);

		// Set to the allocation number from the CRT leak report to break on that allocation
		// _crtBreakAlloc = 5374;
	}
};

CrtBreakAllocSetter gCrtBreakAllocSetter;

#endif
